### ISSUE TITLE
React? 1 global context only?

### ISSUE THREAD

**Issue by alloursjournall** [frankcollins3/mine-nugget-ts#34]
I'm able to get string state rendered but the function that changes setState() in the component isn't doing anything.
I copy-pasted the global context file that was working and the same code that works no longer doesn't work with the functions

the state is still rendered correctly.
_also looked into app and i believe i figured how to setup export default Connect from my last commit._

i originally planned to organize the global state by component
Typing this out now that seems the point of global state. to have 1 store.

first proposed solution is:
create state, create state changing functionality, and test that functionality.
the downside is the import of the global state will still be useGame() but that's okay for now.

i've been dealing with this for about an hour [ i post the issue @ 11:41pm]

**Comment by frankcollins3** [comment]
wow what a joke everything i was doing in the context/game that worked. did nothing in the context/find
thats so weird that the string state appears but the setState functionality does nothing.
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
the developer is the problem:
the problem that global state seems to solve is that you declare these different expressions in different places.
and it is solved by declaring the same amount of expressions but in 1 place.

global state. globe. earth. universe.
uni === 1
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

this seems an example of working so heads-down you don't see the post-it note above your forehead 


[11:50am] goodbye hour of existence :9
